### ISSUE TITLE
Different Peak Usage on different machines for the same script?

### ISSUE THREAD

**Issue by RAbraham** [pythonspeed/filprofiler#183]
Hi,
I just wanted to confirm that Peak Memory Usage is the maximum memory used at a particular moment and not cumulative in any way?

I run the same script on two different machines and I get different peak memory usage. Also, this code normally runs in a docker container restricted at 4GB and it averages at around 1.4GB when I look at `docker stats`. So I'm not sure how to interpret these numbers. Appreciate any help.

- Laptop(32G RAM). filprofiler says peak memory ~6000MiB
![image](https://user-images.githubusercontent.com/214189/118174598-08c29600-b3fd-11eb-985c-7c6ff02588f3.png)

- Server(64G RAM). filprofiler says peak memory ~11000MiB
![image](https://user-images.githubusercontent.com/214189/118174437-cdc06280-b3fc-11eb-842e-edf299b848b1.png)

I have only attached a snapshot of the major memory consumer. But the other significant consumer increased from 1GB(on laptop) to 1.8GB(on server)

**Comment by RAbraham** [comment]
I disabled GPU and the above usage became more predictable. Also, other memory usage across the laptop and server was more consistent(though the CPU loading of the above model still showed a difference from 500MiB on laptop to 1.4 GiB on the server. I'm guessing this is a behaviour of ktrain/tensorflow). Closing this ticket. 
btw, thank you very much for making this tool. It's so convenient. Like you heard the cries of ML Engineers everywhere :).

**Comment by itamarst** [comment]
Hi,

Thanks for reporting this, sorry it was confusing.

Want to make sure there are no bugs, so have some follow-up questions, and also I should explain the limitations (and improve the output so it's documented and clearer).

Fil measures _allocated_ memory, i.e. memory requested from the OS. `docker stats` would measure _resident_ memory, memory that is currently in RAM. 

1. If the data gets dumped from RAM to swap, Fil still counts it but it's not counted as resident in RAM.
2. If the memory is a large chunk of all zeros, on Linux no RAM is used by OS until you actually modify that memory, but Fil will still count it.
3. If you have memory that only gets freed on garbage collection (this will happen if you have circular references in your data structures), memory can be freed at inconsistent times across different runs, especially if you're using threads.

Questions I have:

1. Were you in fact using GPU? That would result in confusing results, yes.
2. What version Fil are you using? Make sure you're always using the latest version, been fixing a bunch of bugs.
3. Was the meaning of the reversed graph clear, since you included that?
4. Did Fil actually help you spot a specific problem?
5. Mind if I quote you in the documentation? "Thank you very much for making this tool. It's so convenient. Like you heard the cries of ML Engineers everywhere :)  — Rajiv Abraham"

**Comment by RAbraham** [comment]
Thanks for the quick reply!
The Fil memory counting explanation sounds good. The only thing I don't understand is point 2. (memory being a large chunk of zeros). Is there somewhere I can read and understand this better? When you say that 'memory is a large chunk of all zeros', do you mean 'data' instead of memory?

Re: the questions
1. Yes, I was using GPU before. I think it has to do with the memory growth feature in Tensorflow. I disabled GPU with `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`. I don't have the exact numbers but it went down from ~4.5GB to 500MB on laptop for the `ListPhysicalDevices()` region of code.
2. filprofiler==2021.5.0
3. Yes, it was for me. I included it in case you wanted to inspect it.
4. So far, Fil showed me(with the reversed graph) that I have to consider GPU (or disable it) as our production servers don't run on GPU. My current use case is going to be to break down the big memory consumers in my program for production memory planning. Then I'll use it to detect code which can be optimized. The graph seems to be good for that.
5. Please do quote me. I know that you like to collect quotes from end users. So the 'sensationalism' was intentional(and true :) )

Questions:
1. Did previous versions of Fil not consider GPU? IIRC, I remember running similar code and it never showed 6GB on the laptop. At that time, I didn't disable GPU either.

**Comment by itamarst** [comment]
> When you say that 'memory is a large chunk of all zeros', do you mean 'data' instead of memory?

Yeah, data. So like, if you do `arr = numpy.zeroes((1024, 1024))` that won't take up any RAM until you write to arr.

```python
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
41100
>>> arr = np.zeros((1024, 1024, 100))
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
41100
>>> arr = np.ones((1024, 1024, 100))
>>> resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
852108
```

Fil never looked at GPU memory. Different versions of CUDA and TensorFlow might make a difference though in how memory is allocated between CPU and GPU.

**Comment by RAbraham** [comment]
re: zeroes. Oh, that's very interesting. Thanks for explaining that.

re: CUDA/TF. Yes, definitely possible. I'll keep you posted on how it goes.
