### ISSUE TITLE
Missing a significant memory consumer

### ISSUE THREAD

**Issue by RAbraham** [pythonspeed/filprofiler#192]
Hi Itamar,
If I profile a simple script serializing to json, it works
```python
task =  .. load a big dict ..
tasks = 1000 * [task]
jsons = []
for r in tasks:
    j = json.dumps(r) <=== 607 MiB
    jsons.append(j)

util.write_json(jsons,"dummy.json" )

```
The memory usage shows ~ 607 MiB. `dummy.json` is about 644M on disk

If that piece of code is part of another significant script whose total usage is around 2680 MiB, it does not show up at all. I would think that ~600 MiB is still big enough to show up in the graph

```python

from app import Worker # <=== 1G

task =  .. load a big dict ..

worker = Worker() <===== 278M
result = worker.work(task) <========== 1.36G


jsons = []
for r in result:
    j = json.dumps(r) <==== does not show up
    jsons.append(j)

util.write_json(jsons,"real.json" )

```
The `real.json` on disk is 699M so the `dumps` is significant(relatively). 

Thanks,
Rajiv

**Comment by itamarst** [comment]
So one possibility is that this is because Fil returns the _peak_ memory. So it's quite possible for very large allocations not to show up if they were not present during the peak.

In this case, if peak was during the execution of `work()`, the memory usage when the JSON was allocated would be ~600MB less than peak. As such it doesn't matter how much you optimize it, peak requirement would still be unchanged. Once you optimize `work()`'s memory usage, it would start showing up if it was the new bottleneck.

Might be a bug too, of course, or something else, but that seems the most likely reason at a first glance.

**Comment by RAbraham** [comment]
that makes sense. Thanks!
