### ISSUE TITLE
Missing Allocations in Top2vec Machine Learning Code

### ISSUE THREAD

**Issue by dbl001** [pythonspeed/filprofiler#369]
I am profiling Top2vec with filprofiler on OS X Monterey.  

https://github.com/ddangelov/Top2Vec

Top2vec uses BERT distributed word vectors with a Hugging Face sentence transformer model as well as word clouds, umap, ipywidgets, etc.
Many of the allocations are missing.

<img width="2560" alt="Screen Shot 2022-05-18 at 6 52 02 AM" src="https://user-images.githubusercontent.com/3105499/169058471-da625d32-f5a0-4b89-bd5a-8bfea734d236.png">

Python 3.8.13 
Monterey 12.4

Test script:
```
import numpy as np 
import pandas as pd
import sys
import faulthandler
import json
import os
import ipywidgets as widgets
from IPython.display import clear_output, display
from top2vec import Top2Vec

faulthandler.enable(file=sys.stderr, all_threads=True)

def filter_short(papers_df):
    papers_df["token_counts"] = papers_df["text"].str.split().map(len)
    papers_df = papers_df[papers_df.token_counts > 5000].reset_index(drop=True)
    papers_df.drop('token_counts', axis=1, inplace=True)

    return papers_df

papers_prepared_df = pd.read_feather("/Users/davidlaxer/Downloads/archive-2/covid_papers_may_9_2022.feather")
papers_filtered_df = filter_short(papers_prepared_df)

top2vec_trained = Top2Vec(documents=papers_filtered_df.text.tolist(),  split_documents=True, embedding_batch_size=128, embedding_model="universal-sentence-encoder",  use_embedding_model_tokenizer=True, embedding_model_path="/Users/davidlaxer/Downloads/universal-sentence-encoder_4", workers=6)
```
I ran a simple test and the filprofiler process grew to 128+ gigabytes.
Any ideas?

**Comment by itamarst** [comment]
Here's the background:

1. In order to reduce the size of the output, Fil filters out the last 5% or so of allocations from the display if there are more than a thousand or so different allocation sites (I forget the exact thresholds). This is not a problem for profiling purposes because you want to optimize the large allocations anyway, so who cares if there's a bunch of tiny allocations you're not seeing.
2. Fil shows _peak_ memory, so allocations that don't add to the peak aren't shown.

So on the face of it the visualization part is working as expected: it thinks that the string splitting is the biggest allocation, that reading the feather is the second biggest allocation, and the rest of the allocations are so tiny in comparison that it doesn't show them.

There may still be a bug, of course, the 40GB number shown, or the 128GB number you report, may indicate a bug in the memory profiling part. Then again, maybe not. How big is the feather file?

Notice BTW that `.str.split().map(len)` is actually using much more memory than you'd expect. First it constructs a list of strings for every line in the file, and _after that_ it does the `len()`. Since you don't care about the individual strings this is quite a lot of memory being used temporarily.

If you have 1,000,000 lines with 20 words each, you are storing 20,000,000 words in memory, temporarily.

An alternative would be `papers_df["text"].map(lambda s: len(s.split()))` which would be much more memory efficient (and for this particular operation, likely just as fast).

**Comment by dbl001** [comment]
Thank You!
The feather file is 4gb.
```
% ls -l /Users/davidlaxer/Downloads/archive-2/covid_papers_may_9_2022.feather
-rw-r--r--  1 davidlaxer  staff  4661203834 May  9 11:39 /Users/davidlaxer/Downloads/archive-2/covid_papers_may_9_2022.feather

```
I tried your suggestion 
```
def filter_short(papers_df):
    papers_df["token_counts"] = papers_df["text"].map(lambda s: len(s.split()))
    papers_df = papers_df[papers_df.token_counts > 5000].reset_index(drop=True)
    papers_df.drop('token_counts', axis=1, inplace=True)

    return papers_df

```
<img width="2560" alt="Screen Shot 2022-05-18 at 8 25 52 AM" src="https://user-images.githubusercontent.com/3105499/169080852-b6a84f99-ec4a-4a38-90a0-39fd4af4f80b.png">

**Comment by itamarst** [comment]
This may be accurate, depending what data is in the columns. 

* Python strings can use rather more memory than you'd expect, especially if you have non-ASCII characters. In theory you may be able to save memory by using the new string dtype (https://pythonspeed.com/articles/pandas-string-dtype-memory/) but I don't see a Pandas option for using that when loading from feather files...
* If one of the columns is a list of integers, say, it will use much more memory in Python than it will in the feather format (not sure if that's possible to represent in feather, but just as an example). 
* Feather supports compression, so the loaded data may be much bigger.

Other options:

* Convert to Parquet, use Dask's Pandas emulation (https://docs.dask.org/en/latest/dataframe.html)
* https://vaex.io has native support for Feather, I think, and can process large files without reading them completely into memory.
 * https://www.pola.rs/ may also have better memory usage, not sure.
* Convert feather to Parquet, use DuckDB's ability to read parquet directly: https://duckdb.org/docs/data/parquet

**Comment by itamarst** [comment]
Taking a step back: the broader picture here, I just realized, is that you want to profile top2vec but the steps leading up to using it are hiding that memory usage from you.

So one thing you can do is use Fil's API to only profile part of the code, the part _after_ you load the dataframe. And then the massive usage from the dataframe loading won't be counted. See https://pythonspeed.com/fil/docs/api.html, or https://pythonspeed.com/fil/docs/jupyter.html if you want to use Jupyter.

**Comment by dbl001** [comment]
I tried adjust the filter_short threshold so that Top2vec would train on more documents, filprof ran upto 108 gigabyte so I terminated it.

![peak-memory](https://user-images.githubusercontent.com/3105499/169117769-44b47b5e-b96b-4f56-b246-30eb10db5462.svg)
![peak-memory-reversed](https://user-images.githubusercontent.com/3105499/169117776-95d5723b-1d38-4d0a-96fb-8ddfbebb687d.svg)

Now, I'm trying to profile top2vec
e.g. 
```
$ fil-profile python notebooks/test.py


top2vec_trained = profile(lambda: top2Vec(documents=papers_filtered_df.text.tolist(),  split_documents=True, embedding_batch_size=128, embedding_model="universal-sentence-encoder",  use_embedding_model_tokenizer=True, embedding_model_path="/Users/davidlaxer/Downloads/universal-sentence-encoder_4", workers=6), "/tmp/fil-result")
```

**Comment by dbl001** [comment]
![peak-memory](https://user-images.githubusercontent.com/3105499/169130517-9b7ad1f2-4f23-4dcd-9267-fb4a9329bd82.svg)
![peak-memory-reversed](https://user-images.githubusercontent.com/3105499/169130527-7117dc38-51f1-4245-8e8c-e611e97a97b5.svg)

**Comment by itamarst** [comment]
So, looks like you're getting reasonable data now? Note you can click on a stacktrace to zoom in on it.

**Comment by dbl001** [comment]
Yep.  Why are there three columns displayed and four in the reversed?

**Comment by itamarst** [comment]
Reversed tracks allocations starting from the bottom frame, so the stacks merge in different places. So e.g. if you end up calling line 2007 of example.py in a bunch of places and it ends up allocating a bunch of memory, in the regular flamegraph that'll be at the bottom of multiple stacks, but in reversed one it will be the top frame. My guess is the stack that is being split in two is the one on the right in the normal flamegraph, but harder for me to tell since I can't interact with it.

**Comment by dbl001** [comment]
Yes.  Thanks!
