### ISSUE TITLE
Wheels for python 3.12 are missing

### ISSUE THREAD

**Issue by thebaptiste** [pythonspeed/filprofiler#522]
Could you please provide wheels for Python 3.12 on pypi ?

Thanks

**Comment by emorice** [comment]
A user needed a wheel for 3.12 on linux today and it successfully compiled from your [522-wheels-for-python-312-are-missing](https://github.com/pythonspeed/filprofiler/tree/522-wheels-for-python-312-are-missing) branch with especially the linker fix being helpful. Is it the mac support which is blocking? If so I'll just drop that a partial release of the linux wheels would definitely be of interest to some users. Thanks for the great tool btw!

**Comment by itamarst** [comment]
I was actually having issues linking locally, and then got distracted. I'll try to get back to it.

**Comment by itamarst** [comment]
I think I figured out the linking issues.

**Comment by ogencoglu** [comment]
Any updates?

**Comment by rouge8** [comment]
This also applies to Python 3.13 now

**Comment by itamarst** [comment]
Yeah... I have been distracted by paid work, being sick for a month, vacation, political organizing, etc.. The main bottleneck is that the output is _wrong_ on Python 3.12 (and presumably 3.13) and I can't figure out why. If anyone who understands Python's C API wants to poke at the branch, that'd be helpful, but I will try again.

**Comment by itamarst** [comment]
Some progress in understanding:

- Tests fail on 3.12 because `mmap.mmap()` used to not release GIL, and now does as of 3.12.
- Put another way, Fil fails to profile correctly in some cases when GIL is not held.
- I was relying on `PyTrace_C_CALL` op in Python's tracing/profiling API to get this info, but... turns out that doesn't get used in some cases! In particular, for `mmap.mmap()`, perhaps because it's a type constructor rather than a standalone function. This seems like a bug in CPython to me, which I guess I'll go file, but even if it'll get fixed that is not very helpful anytime soon.

**Comment by itamarst** [comment]
Moving 3.13 to new issue so I can get 3.12 wheels out. Hopefully will be much faster process!

**Comment by itamarst** [comment]
Wheels for 3.12 are now up on PyPI.

**Comment by itamarst** [comment]
And wheels for 3.13 are now up on PyPI too.

**Comment by thebaptiste** [comment]
Thanks
